---
language: go

sudo: required

services:
  - docker

before_install:
  - go get github.com/jteeuwen/go-bindata/...
  - go-bindata resources/

before_script:
  - docker-compose build
  - docker-compose up -d
